openapi: 3.1.0
info:
  title: Tetra Master
  version: 1.0.1
  summary: API for the FF9 card game Tetra Master
  description: >-
    Interact with data related to the Final Fantasy IX
    card game Tetra Master
  termsOfService: https://github.com/matthewmurphy
  contact:
    name: Matt Murphy
    url: https://github.com/matthewmurphy
    email: matt@acoustictoast.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
    description: Local development environment
tags:
  - name: Cards
    description: Endpoints that interact with cards
paths:
  /cards:
    summary: Interact with the complete list of cards
    description: >-
      Provides the GET operation for the list of existing cards
    get:
      operationId: getCards
      summary: Get a list of cards
      description: >-
        Gets a list of all Tetra Master cards. Can be filtered with
        query parameters
      tags:
        - Cards
      parameters:
        - name: id
          in: query
          description: The ID of an individual card to retrieve
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of the requested cards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
components:
  schemas:
    Card:
      type: object
      required:
        - name  
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string